version: "3.4"

services:
  bgmi:
    build: .
    image: bgmi
    container_name: bgmi
    volumes:
      - "./:/mount/"
      - "/mnt/cloud:/mnt/cloud"
    restart: unless-stopped
    environment:
      - BGMI_PATH=/mount/data
    ports:
      - "8085:8080"
